// SPDX-License-Identifier: MIT
//
// Copyright (C) 2025 Antonio Niño Díaz

#ifndef DSWIFI_COMMON_RANDOM_H__
#define DSWIFI_COMMON_RANDOM_H__

#include <stdint.h>

// random.c assumes that Wifi_RandomAddEntropy is only called from ARM7, so
// enforce that that's the case by only declaring it there.
#ifdef ARM7
// Add a value to the entropy pool in the hopes that it's unpredictable.
// If it is, the numbers generated by Wifi_Random also become less predictable,
// and our cryptography becomes stronger. If it's not, no harm is done aside
// from the time wasted stirring it into the pool. This function normally only
// adds the value to a buffer to be crunched later, but for every 256 bytes, the
// hasher's compression function is triggered a single time. This is expensive,
// taking about 5,850 cycles, or 175 microseconds, during which time interrupts
// are disabled.
void Wifi_RandomAddEntropy(uint32_t value);
#endif

// Generate a single random number, uniformly distributed in the range [0,2^32).
// In practical terms, this number is exactly as unpredictable as the stream of
// data that's been fed to Wifi_RandomAddEntropy up to this point.
//
// This can be a heavy operation. Only call this function if you need
// cryptographically secure random numbers.
uint32_t Wifi_Random(void);

#endif // DSWIFI_COMMON_RANDOM_H__
