// SPDX-License-Identifier: MIT
//
// Copyright (C) 2025 Antonio Niño Díaz

#ifndef DSWIFI_COMMON_RANDOM_H__
#define DSWIFI_COMMON_RANDOM_H__

#include <stdint.h>

// random.c assumes that these functions are only called from ARM7, so enforce
// that that's the case by only declaring them there.
#ifdef ARM7
// Add bytes to the entropy pool in the hopes that they're unpredictable.
// If they are, the numbers generated by Wifi_Random also become less
// predictable, and our cryptography becomes stronger. If they're not, no harm
// is done aside from the time wasted stirring them into the pool. This function
// normally only adds the bytes to a buffer to be crunched later, but for every
// 256 bytes, the hasher's compression function is triggered a single time. This
// is expensive, taking about 5,850 cycles, or 175 microseconds, during which
// time interrupts are disabled.
void Wifi_RandomAddEntropyBytes(const void *in, size_t inlen);

// Convenience function to add 4 bytes of entropy from a 32-bit integer.
void Wifi_RandomAddEntropy(uint32_t value);
#endif

// Generate exactly outlen random bytes. In practical terms, this stream of
// bytes is exactly as unpredictable as the stream of data that's been fed to
// Wifi_RandomAddEntropy[Bytes] up to this point.
//
// This can be a heavy operation. Only call this function if you need
// cryptographically secure random numbers.
void Wifi_RandomBytes(void *out, size_t outlen);

// Generate a single random number, uniformly distributed in the range [0,2^32),
// using Wifi_RandomBytes under the hood to do so.
//
// This can be a heavy operation. Only call this function if you need
// cryptographically secure random numbers.
uint32_t Wifi_Random(void);

#endif // DSWIFI_COMMON_RANDOM_H__
